{{- if .Values.serviceMonitor.enabled | default false }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "safeguard.fullname" . }}
  labels:
    {{- include "safeguard.labels" . | nindent 4 }}
    release: prometheus
spec:
  selector:
    matchLabels:
      {{- include "safeguard.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - {{ include "safeguard.namespace" . }}
{{- end }}
