apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "safeguard.fullname" . }}
  labels:
    {{- include "safeguard.labels" . | nindent 4 }}
  annotations:
    vault.hashicorp.com/agent-inject: "true"
